### PR TITLE
Fix incomplete like command locks arrow key

### LINKED ISSUE #229: Unable to move the caret after typing "like " in the command box

### PR DESCRIPTION
**Pull request by moziliar**
closes #229

### CODE REVIEW

**Comment by gary-lgy** [comment]
Did you take a look at #228? It's referenced in the issue.

**Comment by moziliar** [comment]
@gary-lgy I can try.

**Comment by gary-lgy** [comment]
@moziliar :rofl: you don't need to try, I already fixed it in my PR

**Comment by moziliar** [comment]
@gary-lgy wut... ok

**Pull request closed without merging**
